In [1]:
from torch.utils import data
import os
import numpy as np
from PIL import Image
#from mypath import Path
#from torchvision import transforms
#import dataloaders.custom_transforms as tr #Why no module found ? Because its not initialized ? How to do that?
import cv2 as cv
import matplotlib.pyplot as plt
#this class is based on Cityscapes Dataset in the given repo..

In [2]:
path="./../../Data/new/"

In [3]:
def convert_deepSegMask_toMask(path,imgname): 
    im=cv.imread(path+imgname)#bgr
    im=cv.cvtColor(im, cv.COLOR_BGR2RGB)
    #unique=np.unique(im, axis=0)
    #print(np.unique(unique,axis=1))
    #print(unique.shape)
    print(im.shape)
    """
    This is hardcoded way of replacing specific colors to 0,1,2...indexes
    self.void_classes = [0]
        self.valid_classes = [0,1,2,3,4,5,6,7,8]
        self.class_names = ['Background','Limonium', 'Spartina', 'Batis', 'Other', 'Spart_dead', \
                            'Juncus', 'Sacricornia', 'Borrichia']
                            

    """
    mask1=cv.inRange(im, (255,63,42),(255,63,42))
    mask_1=np.where(mask1==255,1,0)

    mask2=cv.inRange(im,(127,255,140),(127,255,140))
    mask_2=np.where(mask2==255,2,0)
    mask3=cv.inRange(im,(101,85,255),(101,85,255))
    mask_3=np.where(mask3==255,3,0)

    mask4=cv.inRange(im,(255,202,28),(255,202,28))
    mask_4=np.where(mask4==255,4,0)


    mask5=cv.inRange(im,(113,255,221),(113,255,221))
    mask_5=np.where(mask5==255,5,0)


    mask6=cv.inRange(im,(212,70,255),(212,70,255))
    mask_6=np.where(mask6==255,6,0)


    mask7=cv.inRange(im,(99,187,255),(99,187,255))
    mask_7=np.where(mask7==255,7,0)


    mask8=cv.inRange(im,(255,56,169),(255,56,169))
    mask_8=np.where(mask8==255,8,0)

    mask_arr=np.array([mask_1,mask_2,mask_3,mask_4,mask_5,mask_6,mask_7,mask_8])
    mask=mask_arr.sum(axis=0)
    print(np.unique(mask))
    cv.imwrite(path+imgname,mask)

In [4]:
#script to convert masks from deep segments to Masks that semantic segmentation models expect. 
files=os.listdir(path)
for file in files:
    if file.endswith("mask.png"):
        convert_deepSegMask_toMask(path,file)

(667, 857, 3)
[0]
(667, 857, 3)
[0 3 8]
(667, 857, 3)
[0 3 8]
(666, 858, 3)
[0 3 4 8]
(666, 857, 3)
[0 2 4 5 7]
(667, 858, 3)
[0 2 5 7]
(667, 857, 3)
[0 7]
(667, 857, 3)
[0 4 7]
(667, 857, 3)
[0 2 4 5 7]
(667, 857, 3)
[0 2 4 5 7]
(667, 858, 3)
[0 3 6 7]
(667, 857, 3)
[0 3 4 7]
(667, 857, 3)
[0 4 5 7]
(667, 857, 3)
[0 2 4 7]
(667, 858, 3)
[0 2 5 7]
(667, 857, 3)
[0 7]
(667, 858, 3)
[0 2 4 5 7]
(667, 857, 3)
[0 7]
(667, 857, 3)
[0]
(666, 857, 3)
[0]
(667, 857, 3)
[0 1 3 6 7]
(667, 858, 3)
[0 7]
(667, 858, 3)
[0 1 3 4 7]
(666, 857, 3)
[0 3 4 7 8]
(667, 857, 3)
[0 1 3 4 7]
(666, 857, 3)
[0 2 4 5 6 7]
(667, 857, 3)
[0 2 5 7]
(667, 857, 3)
[0 2 5 7]
(667, 857, 3)
[0 2 5 7]
(667, 857, 3)
[0 2 4 5 7]
(667, 857, 3)
[0]
(666, 857, 3)
[0]
(667, 858, 3)
[0 4 7]
(667, 857, 3)
[0 2 5]
(666, 857, 3)
[0 2 5]
(667, 857, 3)
[0 2 4 5]
(666, 857, 3)
[0 2 5]
(667, 858, 3)
[0 2 4]
(667, 857, 3)
[0 2 4 5]
(666, 858, 3)
[0 2 4 5]
(666, 857, 3)
[0 2]
(666, 858, 3)
[0 2 5]
(666, 857, 3)
[0 2 5]
(667, 857, 3)
[0